version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    env_file:
      - .local.env
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./mongo/data:/data/db
    networks:
      - triton

networks:
  triton:
